name: Bug Report
description: Create a report to help us improve
labels: ["bug"]

body:
  - type: checkboxes
    attributes:
      label: Already reported? *
      description: Before reporting a bug, check if it already exists in the open or closed issues.
      options:
        - label: I have searched the existing open and closed issues.
          required: true

  - type: textarea
    id: desc
    attributes:
      label: Describe the bug
      description: "What went wrong?"
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: "How can someone else reproduce the issue?"
    validations:
      required: true

  - type: textarea
    id: beh
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Images, Videos
      description: |
        Anything that can help. Please always ATTACH and not paste them.
    validations:
      required: false
